version: '3.7'

services:
  server:
    image: nginx:latest
    container_name: server
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - sayit-server
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot -w /var/www/certbot --force-renewal --email agovind@ucsd.edu -d server.agilelovers.org --agree-tos


  sayit-server:
    container_name: sayit-server
    build:
      context: .
      dockerfile: Dockerfile
    image: sayit-server:latest
    restart: unless-stopped
    depends_on:
      - sayit-db

  sayit-db:
    image: mongo:latest
    container_name : sayit-db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    restart: unless-stopped
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    driver: local
