version: '3.8'

services:
  sayit-server:
    container_name: sayit-server
    build:
      context: .
      dockerfile: Dockerfile
    image: sayit-server:latest
    depends_on:
      - sayit-db
    ports:
      - "8080:8080"

  sayit-db:
    image: mongo:latest
    container_name : sayit-db
    command: mongod
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    driver: local