package org.agilelovers.server.user;


import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public
class ReducedUserDocument {
    @ApiModelProperty(notes = "Unique ID generated by MongoDB")
    private String id;

    @ApiModelProperty(notes = "Username of the user")
    private String username;

    @ApiModelProperty(notes = "Email of the user")
    private String email;
}