package org.agilelovers.server.user;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;
import org.agilelovers.server.email.config.EmailConfigDocument;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

@Document("sayit-users")
@Data
@SuperBuilder
@AllArgsConstructor
@NoArgsConstructor
@ApiIgnore
public class UserDocument {

    @ApiModelProperty(notes = "Unique ID generated by MongoDB")
    @Id
    private String id;

    @ApiModelProperty(notes = "Username of the user", required = true)
    @NotNull
    @NotBlank
    @Email
    @Indexed(name = "username", unique = true)
    private String username;

    @ApiModelProperty(notes = "Password of the user", required = true)
    @NotNull
    @NotBlank
    @NotEmpty
    private String password;

    @ApiModelProperty(notes = "Document containing email configuration, given during email setup")
    private EmailConfigDocument emailInformation;
}