package org.agilelovers.server.user;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

@Document("sayit-users")
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class UserDocument {

    @ApiModelProperty(notes = "Unique ID generated by MongoDB")
    @Id
    private String id;

    @ApiModelProperty(notes = "Username of the user", required = true)
    @NotNull
    @NotBlank
    @Email
    @Indexed(name = "username", unique = true)
    private String username;

    @ApiModelProperty(notes = "Email of the user")
    @Email
    private String email;

    @ApiModelProperty(notes = "Password of the user", required = true)
    @NotNull
    @NotBlank
    private String password;
}
