package org.agilelovers.common.models;


import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public
class ReducedUserModel {
    @ApiModelProperty(notes = "Unique ID generated by MongoDB")
    private String id;

    @ApiModelProperty(notes = "Username of the user")
    private String username;
}