package org.agilelovers.common.documents;

import io.swagger.annotations.ApiModelProperty;
import io.swagger.v3.oas.annotations.Hidden;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import springfox.documentation.annotations.ApiIgnore;

import java.util.Date;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;


@Document("sayit-emails")
@Data
@Builder
@AllArgsConstructor
@Hidden
public class EmailDocument {
    @ApiModelProperty(notes = "Unique ID generated by MongoDB")
    @Id
    private String id;

    @ApiModelProperty(notes = "Timestamp this question was created at")
    @CreatedDate
    private Date createdDate;

    @ApiModelProperty(notes = "User ID associated with this email", required = true)
    @NotEmpty
    private String userId;

    @ApiModelProperty(notes = "The email prompt used to generate the body", required = true)
    @NotBlank
    private String entirePrompt;

    // Attach display name to end
    @ApiModelProperty(notes = "The body of the email", required = true)
    @NotNull
    @NotBlank
    private String body;
}


