package org.agilelovers.server.email;

import io.swagger.annotations.ApiModelProperty;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.util.Date;

public class EmailInformationDocument {
    @ApiModelProperty(notes = "Unique ID generated by MongoDB")
    private String id;

    @ApiModelProperty(notes = "Timestamp this question was created at")
    @CreatedDate
    private Date createdDate;

    @ApiModelProperty(notes = "User ID associated with this email", required = true)
    @NotNull
    @NotBlank
    private String userId;

    @ApiModelProperty(notes = "The email prompt used to generate the body", required = true)
    @NotNull
    @NotBlank
    private String prompt;

    // Attach display name to end
    @ApiModelProperty(notes = "The body of the email", required = true)
    @NotNull
    @NotBlank
    private String body;

    @ApiModelProperty(notes = "Email of user email will be sent towards", required = true)
    private String emailOfUserSentTowards;
}
