package org.agilelovers.server.command;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

@Document("sayit-commands")
@Data
@Builder
@AllArgsConstructor
public class CommandDocument {
    @ApiModelProperty(notes = "Unique ID generated by MongoDB")
    @Id
    private String id;

    @ApiModelProperty(notes = "User ID associated with this command", required = true)
    @NotNull
    @NotBlank
    private String userId;

    @ApiModelProperty(notes = "The command transcribed by OpenAI Whisper", required = true)
    @NotNull
    @NotBlank
    private String command;

    @ApiModelProperty(notes = "The output of the command on the client's device stored in our database")
    private String output;
}
