package org.agilelovers.server.email.config;

import io.swagger.annotations.ApiModelProperty;
import io.swagger.v3.oas.annotations.Hidden;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.agilelovers.server.common.URLConstraint;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;


@Document("sayit-email-config")
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Hidden
public class EmailConfigDocument {

    @ApiModelProperty(notes = "Unique ID generated by MongoDB")
    @Id
    private String id;

    @ApiModelProperty(notes = "ID Of User this email information relate to", required = true)
    @NotNull
    private String userID;

    @ApiModelProperty(notes = "first name of user during email setup")
    @NotNull
    private String firstName;

    @ApiModelProperty(notes = "last name of user during email setup")
    @NotNull
    private String lastName;

    @ApiModelProperty(notes = "Email of the user inputted during email setup")
    @NotNull
    @Email
    private String email;

    @ApiModelProperty(notes = "Email password of the email given by user in email setup")
    @NotNull
    private String emailPassword;

    @ApiModelProperty(notes = "Display name to be shown on email sent, given in email setup")
    @NotNull
    @Indexed(name = "display name")
    private String displayName;

    @ApiModelProperty(notes = "SmtpHost of email given during email setup")
    @URLConstraint
    @NotNull
    private String smtpHost;

    @ApiModelProperty(notes = "tlsPort of email given during email setup")
    @NotNull
    private String tlsPort;
}
